Solutions for third topic
js-tasks-ru/js-20200928_blend2012 pull request #3
Opened 2020-10-06 22:44 UTC by VasiliiKirillov

2020-10-06 22:51 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-10-06 23:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-07 00:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-07 18:08 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    for (const prop of path.split('.')) {
в цикле не стоит выполнять операцию `path.split('.')` так как это действие будет выполнено на каждуйю итерацию цикла

2020-10-07 18:09 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  return obj ? Object.fromEntries(Object.entries(obj).map(([key, value]) => [value, key])) : obj;
старайтесь разбивать такую цепочку вызовов на несколько строк

2020-10-07 18:10 UTC, dosandk requested changes
все решения кроме creteGetter принимаются, внесите изменения согласно комменту

2020-10-07 19:21 UTC, VasiliiKirillov commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  return obj ? Object.fromEntries(Object.entries(obj).map(([key, value]) => [value, key])) : obj;
Могу я попросить вас привести пример хорошего разбиения подобной строки? Разбить построчно тернарник? Разбить построчно конвертацию объекта с помощью методов .fromEntries и .entries? Вынести в отдельную функцию коллбек в map?

2020-10-07 19:22 UTC, VasiliiKirillov commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    for (const prop of path.split('.')) {
fixed

2020-10-07 19:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-08 10:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-09 19:29 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  return obj ? Object.fromEntries(Object.entries(obj).map(([key, value]) => [value, key])) : obj;
В данном случае можно сделать вот так:
```
if (obj) {
  const entries = Object.entries(obj);
  const invertedEntries = entries.map(([key, value]) => [value, key]));

  return Object.fromEntries(invertedEntries);
}
```  
и обойтись без тернарника.

Какого-то "золотого" правила разбиения нет. Старайтесь просто разбивать такие длинные строки на несколько по приниципу: "одна строка - одна операция"

2020-10-09 19:30 UTC, dosandk approved these changes
good 👍

2020-10-09 19:30 UTC, merged